---
- name: Deploy Website
  hosts: web 
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
    
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    
    - name: Deploy Website
      ansible.builtin.copy:
        src: website/index.html
        dest: /var/www/html/index.html
        mode: '0644' #6-read and write-owner,4-read-user,4-read-other

    - name: Deploy login page
      ansible.builtin.copy:
        src: website/login.html
        dest: /var/www/html/login.html
        mode: '0664'
    - name: Deploy Sing up page
      ansible.builtin.copy:
        src: website/signup.html
        dest: /var/www/html/signup.html
        mode: '0664'
    
